
services:

  challenge:
    image: nginx:latest
    platform: linux/amd64
    ports:
      - "80:80"
    volumes:
      - "./generated/nginx-challenge.conf:/etc/nginx/nginx.conf:ro"
      - "./generated/www/:/var/www/certbot/:ro"
    restart: unless-stopped

  certbot:
    image: certbot/certbot:latest
    platform: linux/amd64
    volumes:
      - "./generated/:/etc/letsencrypt/:rw"
      - "./generated/www/:/var/www/certbot/:rw"
